(() => {
"use strict";
const CONFIG={databasePath:"data/caso.sqlite",maxRows:200}; let db=null,lastEligible=false;
const $=id=>document.getElementById(id), editor=$("sqlEditor"),runBtn=$("runBtn"),result=$("resultArea"),status=$("dbStatus");
const escapeHtml=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
async function post(data){const body=new URLSearchParams({...data,csrf:GAME.csrf});const r=await fetch("api.php",{method:"POST",body});const j=await r.json();if(!r.ok)throw new Error(j.error||"Erro");return j}
async function load(){try{const SQL=await initSqlJs({locateFile:f=>"https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/"+f});const r=await fetch(CONFIG.databasePath,{cache:"no-store"});if(!r.ok)throw new Error("Banco indisponível");db=new SQL.Database(new Uint8Array(await r.arrayBuffer()));status.className="db-status ready";status.innerHTML="<span></span>Banco conectado";runBtn.disabled=false}catch(e){status.className="db-status error";status.innerHTML="<span></span>Falha ao carregar";renderError(e.message)}}
function readonly(sql){const c=sql.replace(/--.*$/gm,"").replace(/\/\*[\s\S]*?\*\//g,"").trim();return /^(SELECT|WITH|PRAGMA\s+table_info)/i.test(c)&&!/\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|REPLACE|ATTACH|DETACH|VACUUM)\b/i.test(c)}
function eligible(sql,hasRows){if(!hasRows)return false;if(GAME.phaseId===1)return true;if(GAME.phaseId===2)return /\bWHERE\b/i.test(sql)&&/\b(AND|OR|LIKE|IN|BETWEEN|ORDER\s+BY)\b/i.test(sql);if(GAME.phaseId===3)return /\bJOIN\b/i.test(sql)&&/\bON\b/i.test(sql);return false}
async function execute(){if(!db)return;const sql=editor.value.trim();if(!sql)return renderError("Digite uma consulta SQL.");if(!readonly(sql))return renderError("São permitidas apenas consultas de leitura (SELECT/WITH).");try{const sets=db.exec(sql),hasRows=sets.some(s=>s.values.length>0);lastEligible=eligible(sql,hasRows);await post({action:"query",phase_id:GAME.phaseId,query:sql,success:lastEligible?1:0});const btn=$("completeBtn");if(btn){btn.disabled=!lastEligible;$("completionHint").textContent=lastEligible?"Consulta válida para o objetivo. Você pode concluir a fase.":"Continue: sua consulta ainda não atende ao objetivo da fase."}if(!sets.length){result.innerHTML='<div class="empty-result"><span>∅</span><p>Nenhum registro encontrado.</p></div>';return}result.innerHTML=sets.map(s=>{const rows=s.values.slice(0,CONFIG.maxRows);return '<div class="query-meta">'+s.values.length+' linha(s)</div><table class="result-table"><thead><tr>'+s.columns.map(c=>'<th>'+escapeHtml(c)+'</th>').join("")+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(v=>'<td>'+escapeHtml(v)+'</td>').join("")+'</tr>').join("")+'</tbody></table>'}).join("")}catch(e){try{await post({action:"query",phase_id:GAME.phaseId,query:sql,success:0})}catch(_){}renderError("Erro SQL: "+e.message)}}
function renderError(m){result.innerHTML='<div class="sql-error">'+escapeHtml(m)+'</div>'}
async function complete(){if(!lastEligible)return;try{const j=await post({action:"complete",phase_id:GAME.phaseId});const v=$("verdict");v.className="verdict success";v.textContent="✓ Fase concluída. Evidência encontrada: "+j.reward; $("completeBtn").disabled=true}catch(e){alert(e.message)}}
function norm(v){return v.trim().toLocaleLowerCase("pt-BR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ")}
async function sha(text){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function accuse(e){e.preventDefault();const ok=(await sha(norm($("suspectInput").value)))===GAME.answerDigest;const v=$("verdict");v.className="verdict "+(ok?"success":"failure");if(ok){const j=await post({action:"complete",phase_id:1,answer:norm($("suspectInput").value)});v.textContent="✓ Caso solucionado. Evidência encontrada: "+j.reward}else v.textContent="✕ As evidências ainda não sustentam essa acusação."}
runBtn.addEventListener("click",execute);$("clearBtn").addEventListener("click",()=>{editor.value="";editor.focus()});editor.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter"){e.preventDefault();execute()}});
$("completeBtn")?.addEventListener("click",complete);$("accusationForm")?.addEventListener("submit",accuse);window.addEventListener("DOMContentLoaded",load);
})();
