<?php
require __DIR__.'/lib.php'; $u=require_user('teacher'); $pdo=db();
$phases=$pdo->query("SELECT p.*,COUNT(CASE WHEN pr.status='completed' THEN 1 END) completed,COUNT(pr.id) started FROM phases p LEFT JOIN progress pr ON pr.phase_id=p.id GROUP BY p.id ORDER BY p.id")->fetchAll();
$students=$pdo->query("SELECT u.id,u.username,u.created_at,u.last_login_at,COUNT(CASE WHEN pr.status='completed' THEN 1 END) completed,COALESCE(SUM(pr.queries_count),0) queries,COALESCE(SUM(pr.attempts),0) attempts FROM users u LEFT JOIN progress pr ON pr.user_id=u.id WHERE u.role='student' GROUP BY u.id ORDER BY u.username")->fetchAll();
$resets=$pdo->query("SELECT r.*,u.username FROM password_reset_requests r JOIN users u ON u.id=r.user_id WHERE r.status='pending' ORDER BY r.requested_at")->fetchAll();
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Painel do professor — Mistério SQL</title><link rel="stylesheet" href="assets/style.css"><script>window.CSRF="<?=h(csrf())?>";</script></head><body><div class="noise"></div>
<header class="app-nav"><a class="brand"><span class="brand-mark">18</span><span>PAINEL DO PROFESSOR</span></a><div class="nav-user"><span><?=h($u['username'])?></span><a href="logout.php">Sair</a></div></header>
<main class="shell dashboard"><span class="eyebrow">ADMINISTRAÇÃO</span><h1>Acompanhamento da turma</h1>
<section class="admin-section"><h2>Liberação das fases</h2><div class="admin-grid"><?php foreach($phases as $p): ?><article class="admin-card"><strong>Fase <?=$p['id']?> · <?=h($p['title'])?></strong><span><?=$p['completed']?> concluíram · <?=$p['started']?> iniciaram</span><?php if($p['developed']): ?><label class="switch-row"><input type="checkbox" data-release="<?=$p['id']?>" <?=$p['released']?'checked':''?>> Liberada</label><?php else: ?><em>Ainda não desenvolvido</em><?php endif ?></article><?php endforeach ?></div></section>
<section class="admin-section"><h2>Solicitações de senha</h2><?php if(!$resets): ?><p class="muted">Nenhuma solicitação pendente.</p><?php endif ?><div class="admin-grid"><?php foreach($resets as $r): ?><article class="admin-card"><strong><?=h($r['username'])?></strong><span>Solicitado em <?=h($r['requested_at'])?></span><div class="reset-row"><input type="text" placeholder="Senha temporária" data-password-for="<?=$r['user_id']?>"><button data-reset="<?=$r['user_id']?>">Redefinir</button></div></article><?php endforeach ?></div></section>
<section class="admin-section"><h2>Resultados dos estudantes</h2><div class="table-wrap"><table class="admin-table"><thead><tr><th>Aluno</th><th>Fases</th><th>Consultas</th><th>Tentativas</th><th>Último acesso</th></tr></thead><tbody><?php foreach($students as $s): ?><tr><td><?=h($s['username'])?></td><td><?=$s['completed']?> / 8</td><td><?=$s['queries']?></td><td><?=$s['attempts']?></td><td><?=h($s['last_login_at']??'—')?></td></tr><?php endforeach ?></tbody></table></div></section>
</main><script>
async function post(data){const body=new URLSearchParams({...data,csrf:window.CSRF});const r=await fetch('api.php',{method:'POST',body});const j=await r.json();if(!r.ok)throw new Error(j.error||'Erro');return j}
document.querySelectorAll('[data-release]').forEach(el=>el.addEventListener('change',async()=>{try{await post({action:'release',phase_id:el.dataset.release,released:el.checked?1:0})}catch(e){el.checked=!el.checked;alert(e.message)}}));
document.querySelectorAll('[data-reset]').forEach(btn=>btn.addEventListener('click',async()=>{const input=document.querySelector('[data-password-for="'+btn.dataset.reset+'"]');try{await post({action:'reset_password',user_id:btn.dataset.reset,password:input.value});location.reload()}catch(e){alert(e.message)}}));
</script></body></html>
